version: '3'

services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ansible-cisco
    volumes:
      - .:/app
    working_dir: /app
    command: sleep infinity

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8085:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
